MCM-38 Update atk-env to use n instead of nvm

diff --git a/atk-env-ionic-mcm b/atk-env-ionic-mcm
--- a/atk-env-ionic-mcm
+++ b/atk-env-ionic-mcm
@@ -1,23 +1,36 @@
 #!/bin/bash
 ENV_NAME=ionic-mcm
+NODE_VERSION=v14.17.3
 
 # exit if environment is already active
 echo $ATK_ENV | grep "$ENV_NAME" &> /dev/null && echo "Environment $ENV_NAME is already active" && exit
 
 previousNodeVersion=`node --version`
-if [ "$previousNodeVersion" != "v14.17.3" ]
-
+if [ "$previousNodeVersion" != "$NODE_VERSION" ]
 	then
-	if ! [ -e /usr/local/opt/nvm/nvm.sh ] &> /dev/null
-		then
-		echo "NVM is not installed -> install now"
-		brew install nvm
-	fi
-	export NVM_DIR=~/.nvm
-	source /usr/local/opt/nvm/nvm.sh
-	echo "Switching to Node v14.17.3"
-	nvm install v14.17.3
-	SWITCHED_NODE_VERSION=true
+	if ! command -v n &> /dev/null
+	  then
+	    echo "n is not installed -> install now"
+	    npm install -g n
+    fi
+    if ! command -v n &> /dev/null
+    	  then
+    	    echo "n installation failed -> trying nvm"
+    	    if ! command -v nvm &> /dev/null
+              then
+              echo "NVM is not installed -> install now"
+              brew install nvm
+            fi
+            export NVM_DIR=~/.nvm
+            source /usr/local/opt/nvm/nvm.sh
+            echo "Switching to Node $NODE_VERSION"
+            nvm install $NODE_VERSION
+            SWITCHED_NODE_VERSION=true
+    else
+      echo "Switching to Node $NODE_VERSION"
+      N_PREFIX=$HOME/.local n $NODE_VERSION
+      SWITCHED_NODE_VERSION=true
+    fi
 fi
 [ -z "$ATK_ENV" ] && export ATK_ENV="$ENV_NAME" || export ATK_ENV="$ATK_ENV,$ENV_NAME"
 export PS1="atk-env:$ATK_ENV:\w $ "
